#![recursion_limit = "128"]

pub mod ast;
pub mod author;
pub mod caveat;
pub mod compnd;
pub mod expdta;
pub mod header;
pub mod jrnl;
pub mod keywds;
pub mod mdltyp;
pub mod nummdl;
pub mod obslte;
pub mod primitive;
pub mod record;
pub mod revdat;
pub mod seqres;
pub mod source;
pub mod split;
pub mod sprsde;
pub mod title;
